version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "."
        target: "/home/rust"
      - /home/rust/target
    ports:
      - 8080:8080
