version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: develop
    volumes:
      - type: bind
        source: "."
        target: "/app"
      - /app/target
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - 8080:8080
    networks:
      - backend
    tty: true
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=pass
networks:
  backend:
    driver: bridge
volumes:
  db:

