version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "./src"
        target: "/app/src"
    healthcheck:
      test: "curl -f http://localhost:8080/health"
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
    driver: bridge

