name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      docker_image_tag_ci: '${{ steps.generate_docker_image_tag.outputs.docker_image_tag_ci }}'
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Cache Docker Build Cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: 'docker-build-cache-${{ github.ref }}-${{ github.sha }}'
          restore-keys: |
            docker-build-cache-${{ github.ref }}
            docker-build-cache-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host
      - name: Generate Docker Image Tag
        id: generate_docker_image_tag
        run: |
          SHA=${{ github.sha }}
          DOCKER_IMAGE_TAG_CI=$(TZ=UTC-9 date '+%Y%m')-${SHA:0:7}
          echo "docker_image_tag_ci=$DOCKER_IMAGE_TAG_CI" >> $GITHUB_OUTPUT
          echo $DOCKER_IMAGE_TAG_CI
      - name: Cache Docker Registry
        uses: actions/cache@v3
        with:
          path: /tmp/docker-registry
          key: 'docker-registry-${{ github.ref }}-${{ github.sha }}'
          restore-keys: |
            docker-registry-${{ github.ref }}
            docker-registry-
      - name: Boot-up Local Docker Registry
        run: >-
          docker run -d -p 5000:5000 --restart=always --name registry -v
          /tmp/docker-registry:/var/lib/registry registry:2
      - name: Wait for Docker Registry
        run: 'npx wait-on tcp:5000'
      - name: Build Docker Image
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          DOCKER_IMAGE_TAG_CI: '${{ steps.generate_docker_image_tag.outputs.docker_image_tag_ci }}'
        run: |
          docker buildx bake \
              --builder="${{ steps.buildx.outputs.name }}" \
              --set='*.cache-from=type=local,src=/tmp/.buildx-cache' \
              --set='*.cache-to=type=local,dest=/tmp/.buildx-cache,mode=max' \
              -f docker-compose.yml -f docker-compose.ci.yml \
              --push
  app-test:
    needs: docker-build
    uses: ./.github/workflows/test.yml
    with:
      docker_image_tag_ci: ${{ needs.docker-build.outputs.docker_image_tag_ci }}
